### ISSUE TITLE
my website doesn't work on my profile

### ISSUE THREAD

**Issue by isamelb** [zero-to-mastery/ZtM-Job-Board#1007]
I get the following wrong address when I click on my website in my profile:
https://zero-to-mastery.github.io/ZtM-Job-Board/www.mindtaxis.com
my website address is https//:mindtaxis.com

**Comment by abhishekakade** [comment]
It is supposed to open your portfolio website in a new tab.

**Comment by StefanSelfTaught** [comment]
Your website opens.
