### ISSUE TITLE
I have added my name but it is not shown on the website

### ISSUE THREAD

**Issue by navendu-pottekkat** [zero-to-mastery/ZtM-Job-Board#1017]
I have added my name and the pull request has been committed yet the site does not show my name!

**Comment by jpsains** [comment]
The persons file has a few errors (it has a few missing curly brackets) Ive fixed with my PR https://github.com/zero-to-mastery/ZtM-Job-Board/pull/1065 

We just need to the fix to be merged and then you'll be able to see yourself.
