### ISSUE TITLE
Link overflowing on the user card

### ISSUE THREAD

**Issue by pixzels** [zero-to-mastery/ZtM-Job-Board#104]
The website link doesn't quite fit the container.

![screen shot 2018-05-05 at 2 46 16 pm](https://user-images.githubusercontent.com/37476411/39661681-5a090d14-5073-11e8-97bb-1d513223da57.png)

**Comment by Ekidoxx** [comment]
It's because that "card" has been added before introducing new structure. Already started working on fixing those
