### ISSUE TITLE
my pull request to be added to the job board was accepted nearly 2 weeks ago, but I don't see my name on the job board 

### ISSUE THREAD

**Issue by YuLogun** [zero-to-mastery/ZtM-Job-Board#1042]
Moreover, it always shows that the number of Total Profiles is 696, whereas it must be way higher judging by the json file with people's profiles

**Comment by jnch009** [comment]
Hi YuLogun, this is super delayed but I recently go to the open source section of Complete Web Dev 2020 and noticed something today. Apparently the JSON is invalid and I have a PR here to fix it. https://github.com/zero-to-mastery/ZtM-Job-Board/pull/1063. Hopefully tomorrow it will be merged. I think the IDs are misleading actually, it seems that some people didn't read the instructions carefully and used the wrong ID therefore showing less.

**Comment by jpsains** [comment]
I spotted the issue too, there was a few curly-brackets missing in the persons file 

I've also fixed it will adding my name PR here: https://github.com/zero-to-mastery/ZtM-Job-Board/pull/1065
