### ISSUE TITLE
My new index.html ,Plz update this

### ISSUE THREAD

**Issue by krishnanath** [zero-to-mastery/ZtM-Job-Board#11]
`<div class="row">
  <div class="cell" data-title="Full Name">
    Krishnanath Maly
  </div>
  <div class="cell" data-title="GitHub">
    <a href="https://github.com/krishnanath" target="_blank">https://github.com/krishnanath</a>
  </div>
  <div class="cell" data-title="Portfolio">
    <a href="https://www.crzna.com" target="_blank">https://www.crzna.com</a>
  </div>
<div class="cell" data-title="Linkedin">
<a href="https://www.linkedin.com/in/krishnanath/" target="_blank">https://www.linkedin.com/in/krishnanath/</a>
</div>
  <div class="cell" data-title="Job Title">
    Full Stack Developer
  </div>
  <div class="cell" data-title="Location">
    Malayattoor KL, INDIA
  </div>
</div>`

**Comment by krishnanath** [comment]
my website www.crzna.com is redirected to Error GitHub page.
https://www.crzna.com URL is not working
Original URL www.crzna.com not working on zero-to-mastery/ZtM-Job-Board

**Comment by SamirJouni** [comment]
Just make a new pull request with the changes, and I or one of the admins will merge it ! :)

**Comment by SamirJouni** [comment]
Nevermind, I already updated it for you ! :)
