### ISSUE TITLE
Production update instructions

### ISSUE THREAD

**Issue by TzuHsuan** [zero-to-mastery/ZtM-Job-Board#114]
Note that any changes to the source will not reflect onto the live page (https://zero-to-mastery.github.io/ZtM-Job-Board) immediately.

The live page is a production build living inside the `gh-pages` branch.
In order to update this

1. Open `package.json` and change `"homepage": "https://[YOURGITHUBUSERNAME].github.io/ZtM-Job-Board"`
2. From the terminal type `npm run deploy`, this will push the production build to your forked repository
3. Submit a PR for the branch

Not sure if there's a better way of doing this, if so please educate me.
And since this is not project specific, not sure if this should go into readme, just going to leave it here for now.

**Comment by Ekidoxx** [comment]
I already suggested using CircleCI for continuous auto build after every commit

**Comment by Ekidoxx** [comment]
And so, the build goes automatically :heart:
