### ISSUE TITLE
Broken Link from udemy couser ZTM web dev to this resource

### ISSUE THREAD

**Issue by felipefaundez7** [zero-to-mastery/ZtM-Job-Board#1330]
On the ZTM 2020 web dev course, section 16, lecture 188, there is this link https://zero-to-mastery.github.io/ZtM-Job-Board/ to the job board. Please update with actual link, thanks @SamirJouni (I didn't know where to put this, hope this is the right place)

**Comment by wmporter** [comment]
The link in the lecture has been updated.
