### ISSUE TITLE
Add my profile

### ISSUE THREAD

**Issue by krittiyaclark** [zero-to-mastery/ZtM-Job-Board#1492]

**Comment by krittiyaclark** [comment]
I forked and created a branch but I could not push it. Any suggestions? Thank you!

`remote: Permission to zero-to-mastery/ZtM-Job-Board.git denied to `

**Comment by krittiyaclark** [comment]
I pushed it and open PR #1493 Thank you!

**Comment by sophiabrandt** [comment]
I will close this issue now. For any questions, let's discuss this in #1493.
