### ISSUE TITLE
Having issues posting to profile

### ISSUE THREAD

**Issue by robrichardsdpt** [zero-to-mastery/ZtM-Job-Board#1690]
I am trying to post update and it is saying that I do not have access.   I tried posting with new branch.

$ git push origin robrichardsdpt-update
ERROR: Permission to zero-to-mastery/ZtM-Job-Board.git denied to robrichardsdpt.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by starique04** [comment]
This issue is (maybe) because you might have cloned the repo directly from the owner and then trying to push the update to that original repo which you don't have access.

You can try first forking the repo to your account then clone it from your account.

**Comment by robrichardsdpt** [comment]
Thank you so much!  I will try that!

**Comment by sophiabrandt** [comment]
@robrichardsdpt Is this issue solved, then?
