### ISSUE TITLE
I have added my name but it is not shown on the Web

### ISSUE THREAD

**Issue by bobbywilliamskgh** [zero-to-mastery/ZtM-Job-Board#1737]
My Pull Request has been merged, but I can't see my name when I search on Job Board Web.

**Comment by bobbywilliamskgh** [comment]
Is it because there is no id in my json file ? but why?

**Comment by motheroftrouble** [comment]
I have exact same issue. I can't even find a record of my merged pull request which was just within the last couple of days.

**Comment by Waseemrajashaik** [comment]
Issue fixed in #1772 pull request

**Comment by StefanSelfTaught** [comment]
Yeah I think it's and error on the JSON with all the persons, it will be resolved.

**Comment by StefanSelfTaught** [comment]
It's resolved 😄
