### ISSUE TITLE
Adding email field/button in contact section.

### ISSUE THREAD

**Issue by Ayaan2907** [zero-to-mastery/ZtM-Job-Board#1802]
There are options for Github, Linkedin, website in the contact section of every card.  An extra button `mailto:<email_id>` will be helpful in contacting a candidate.

**Comment by StefanSelfTaught** [comment]
Feel free to open a pull request 😄

**Comment by Ayaan2907** [comment]
Yes passively working on that.

**Comment by Ayaan2907** [comment]
@StefanSelfTaught Hey, have a look please, Opened PR. #1804
