### ISSUE TITLE
Netlify link 

### ISSUE THREAD

**Issue by ValiNicula** [zero-to-mastery/ZtM-Job-Board#1878]
Hi guys,

Noticed that the Job board deployed on Netlify is not in sync with this one, can you fix that? Would be great! 
Thanks!

**Comment by StefanSelfTaught** [comment]
Which one?

**Comment by ValiNicula** [comment]
Hi Stefan, sorry for the late reply.
I was referring to this : 
https://zero-to-mastery.github.io/ZtM-Job-Board/ in which for example I appear [and this ](https://alumni-board.netlify.app/) which is not in sync and also there are profiles that are loaded 4 times ( search Triece for ex. ) . I hope i make sense.

**Comment by StefanSelfTaught** [comment]
Well we are not really using netlify for this project anymore, just github pages.
