### ISSUE TITLE
Github build action failing

### ISSUE THREAD

**Issue by ngima** [zero-to-mastery/ZtM-Job-Board#2152]
Newly merged pull requests are not reflected on the site due to build failed via Github action.

[Link](https://github.com/zero-to-mastery/ZtM-Job-Board/runs/4907591793?check_suite_focus=true)

**Comment by alfianahar** [comment]
Is there any update when this is will be fixed?

**Comment by ngima** [comment]
I think some of the entries are not in correct format (JSON) based on this https://github.com/zero-to-mastery/ZtM-Job-Board/runs/4975452103?check_suite_focus=true

**Comment by ngima** [comment]
It's been there for 2 months after 64ab38f61abc42b7626683a6779a93bcbce22d85

**Comment by sophiabrandt** [comment]
Solved with [this commit](https://github.com/zero-to-mastery/ZtM-Job-Board/commit/fd60e881434800d817deffd82f8a5e7a218356b9).
