### ISSUE TITLE
feature-test

### ISSUE THREAD

**Issue by cristinelpopescu** [zero-to-mastery/ZtM-Job-Board#2345]
Will be nice to add a photo profile in more shapes like square, round or rounded corners square

**Comment by donmarvex** [comment]
> Will be nice to add a photo profile in more shapes like square, round or rounded corners square

Hello @cristinelpopescu , thank you for opening an issue for adding a new feature.
Currently the profile photo shape is rounded with the property;
```CSS
.br-100 {
    border-radius: 100%;
}
```

#### Please provide clarification on the following areas;

- Could you add a descriptive title for the feature you propose to be added. Currently you only have "feature-test" as the title.
```md
for example;
Feature: Adding x to y component to change or improve z
```
#### Also, a few more questions to clarify;
- Do you intend for this new feature to have square or rounded corners sqaure for _every_ profile photo?
- Should there be an option for _each user_ to be able to select if they want rounded, square or rounded square corners if possible? 
- Could you describe the results of this change on the web application?

**Comment by donmarvex** [comment]
> Should be an option to let the user choose the shape he/she wants. For a square photo, we can fill it with the original shape. For rounded corners, a 5% radius can be a good look: .br-100 { border-radius: 5%; }

Alright @cristinelpopescu, I would want you to propose a design/implentation for this use case so we can run it over with other members and take steps to start working on it, if you want to be assigned to perform this task, it would also be lovely!
