### ISSUE TITLE
map doesn't display all locations

### ISSUE THREAD

**Issue by ProsperousHeart** [zero-to-mastery/ZtM-Job-Board#2592]
I am only able to see 1 pin in the UK

I'm on a PC, Windows 11 I think. Brave browser. (Basically Chrome)

![image](https://user-images.githubusercontent.com/20706498/208202671-068057bb-5156-453d-b7b3-f1531657eeef.png)

**Comment by ProsperousHeart** [comment]
hey @MattCSmith is anyone working on this code at all? or will this be closed because of the stale bot?

**Comment by MattCSmith** [comment]
Apologies for the delay. If you'd like to work on this please feel free to proceed.

**Comment by ProsperousHeart** [comment]
It now shows a lot more, but not near as many as are there

![image](https://user-images.githubusercontent.com/20706498/213278807-a253d25f-7864-472f-9096-9fc627904304.png)

would also be good to have a way to only show from certain countries
