### ISSUE TITLE
Search Bar Disappears 

### ISSUE THREAD

**Issue by esvp7** [zero-to-mastery/ZtM-Job-Board#2602]
Playing around with the website's navbar and after several tests, I noticed the search bar disappeared after clicking 'map', and then the 'JobBoard' logo to go back to the homepage. Once I do that, the search bar is replaced by a text displaying 'Home' which only takes me to the map once clicked, and the search bar reappears only when I refresh. There might be an error in the routing, I'll check it out later. I'm just leaving the issue open.

**Comment by sophiabrandt** [comment]
#2603
