### ISSUE TITLE
Shuffle onClick

### ISSUE THREAD

**Issue by esvp7** [zero-to-mastery/ZtM-Job-Board#2604]
In order to improve the user experience, I think it would be a nice feature to have a button which triggers the profiles shuffle, instead of having to go back and forth between the map and the homepage or refreshing the page once again.

**Comment by MattCSmith** [comment]
Hey @esvp7 would you like to implement this?

**Comment by ProsperousHeart** [comment]
I think this would be a great addition as well. @esvp7 did you want to take this on?

**Comment by ashmeetsmonga** [comment]
@MattCSmith @ProsperousHeart Hello, could I take on this issue?

**Comment by ProsperousHeart** [comment]
> @MattCSmith @ProsperousHeart Hello, could I take on this issue?

By all means!

**Comment by ashmeetsmonga** [comment]
This is the solution that I came up with.
![demo 2](https://user-images.githubusercontent.com/56465357/214296164-ad39c316-0b76-43ec-bb1e-5e6aaf454f83.gif)

@MattCSmith @ProsperousHeart If you are ok with the solution I would raise PR. Any suggestions are welcome

**Comment by MattCSmith** [comment]
> This is the solution that I came up with. ![demo 2](https://user-images.githubusercontent.com/56465357/214296164-ad39c316-0b76-43ec-bb1e-5e6aaf454f83.gif) [ ![demo 2](https://user-images.githubusercontent.com/56465357/214296164-ad39c316-0b76-43ec-bb1e-5e6aaf454f83.gif) ](https://user-images.githubusercontent.com/56465357/214296164-ad39c316-0b76-43ec-bb1e-5e6aaf454f83.gif) [ ](https://user-images.githubusercontent.com/56465357/214296164-ad39c316-0b76-43ec-bb1e-5e6aaf454f83.gif)
> 
> @MattCSmith @ProsperousHeart If you are ok with the solution I would raise PR. Any suggestions are welcome

Looks good to me, nice job

**Comment by adel3li** [comment]
> This is the solution that I came up with. ![demo 2](https://user-images.githubusercontent.com/56465357/214296164-ad39c316-0b76-43ec-bb1e-5e6aaf454f83.gif) [ ![demo 2](https://user-images.githubusercontent.com/56465357/214296164-ad39c316-0b76-43ec-bb1e-5e6aaf454f83.gif) ](https://user-images.githubusercontent.com/56465357/214296164-ad39c316-0b76-43ec-bb1e-5e6aaf454f83.gif) [ ](https://user-images.githubusercontent.com/56465357/214296164-ad39c316-0b76-43ec-bb1e-5e6aaf454f83.gif)
> 
> @MattCSmith @ProsperousHeart If you are ok with the solution I would raise PR. Any suggestions are welcome

good job.
