### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by rahuls321** [zero-to-mastery/ZtM-Job-Board#267]
Why am I getting this error 

> remote: Permission to zero-to-mastery/ZtM-Job-Board.git denied to rahuls321.
> fatal: unable to access 'https://github.com/zero-to-mastery/ZtM-Job-Board.git/': The requestedURL returned error: 403

**Comment by Suba-Sah** [comment]
@rahuls321 how did you fix this issue?
I am also getting this like one here:

> remote: Permission to zero-to-mastery/Animation-Nation.git denied to Suba-Sah.
> fatal: unable to access 'https://github.com/zero-to-mastery/Animation-Nation.git/': The requested URL returned error: 403

**Comment by Suba-Sah** [comment]
Actually, issue is we are pushing our local branch, not our remote forked copy but in the real branch, that could be due to incorrect set of remote url, 
`git remote set-url origin <urltoyourfork>`
 
More details: https://github.com/jlord/patchwork/issues/11600

**Comment by mmestiyak** [comment]
@Suba-Sah  Thank you, i also was facing this problem and solved

**Comment by Kani712** [comment]
I am getting this error. Can someone help to resolve this issue:

remote: Permission to zero-to-mastery/ZtM-Job-Board.git denied to Kani712.
fatal: unable to access 'https://github.com/zero-to-mastery/ZtM-Job-Board.git/': The requested URL returned error: 403
