### ISSUE TITLE
two files exist after cloning from forked  repo

### ISSUE THREAD

**Issue by MichaelBoitmann** [zero-to-mastery/ZtM-Job-Board#2695]
Hi, kindly see this two files that immediately showing up right after cloning this repo from forked ztm-job-board. those are not my files and I can not add my profile because of this. how can I eliminate this files from cloning?

![image](https://user-images.githubusercontent.com/55775047/220077661-24c7a3e2-bd29-43c6-8b78-cb2c6045623f.png)
 Thank you

**Comment by ProsperousHeart** [comment]
Thanks for the heads up. Others have been able to create their profile. What is the issue you're seeing about not being able to create it? We'll look at the duplicates.

**Comment by ProsperousHeart** [comment]
There's only 1 in our list, so perhaps it was deleted since this? Try a new `git pull` from your main branch

**Comment by MichaelBoitmann** [comment]
Thank you. I just double check those names from the main rep and it shows two different file names. One is in cap letter and the second one is in small letter. not sure it it needs two files for one person. I believe this should not be, right?

**Comment by MichaelBoitmann** [comment]
i have a pull request that will add my profile. kindly let me know if there something wrong i did on this process. thank you for your patience.

**Comment by ProsperousHeart** [comment]
#2739 is a 2nd request for this

**Comment by ProsperousHeart** [comment]
you need to [remove the file(s) in question from your git store](https://stackoverflow.com/a/2047477/10474024) so you only are requesting to add your file

**Comment by MichaelBoitmann** [comment]
i created another request after following the deleting procedure before adding my profile. will close this one that will replace with the new request. thank you
