### ISSUE TITLE
Card Style on mobile devices

### ISSUE THREAD

**Issue by devRabbani** [zero-to-mastery/ZtM-Job-Board#2697]
I can fix the style of card on mobile devices

**Comment by ProsperousHeart** [comment]
@devRabbani - feel free to take a stab at it! Link to this issue when you do the PR and we'll merge if all is well (or provide feedback)

**Comment by devRabbani** [comment]
@ProsperousHeart Ok

**Comment by devRabbani** [comment]
@ProsperousHeart  Sorry this is in tachyon css for this first need to check tachyon.....I cant do it right now
