### ISSUE TITLE
Problem with Search Bar when goBack is used

### ISSUE THREAD

**Issue by kaitanidis** [zero-to-mastery/ZtM-Job-Board#2874]
If we search i.e. Greece, it updates with people from Greece. When we click Map or Logo and then return by clicking Home or Logo it remembers search input as Greece but it is not showing into the searchbar.

However, I think it shouldnt remember it at all. Just show all people again. I implement this by adding setSearchfield("") in goBack : 

  function goBack() {
    setMap(!map)
    setMapOrHomeTitle(map ? pageNames.map : pageNames.home)
    **setSearchfield("");**
  }

What do you think?

**Comment by sophiabrandt** [comment]
Can you make a pull request with the proposed changes?
