### ISSUE TITLE
Colliding paths 

### ISSUE THREAD

**Issue by sebashmh** [zero-to-mastery/ZtM-Job-Board#2880]
The following warning appears when cloning and updating the project :

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'Submissions/@Nazmul6180.json'
  'Submissions/@nazmul6180.json'
```

As can be seen in the message, there are two paths with the same user name but different use of initial capital letters. Only one of these files should be preserved.

Thanks.

**Comment by sophiabrandt** [comment]
I have pushed a change and renamed all files starting with an `@`.

Thanks for opening the issue. It should be solved now.

If you encounter any problems, feel free to re-open this issue.
