### ISSUE TITLE
[Feat] Add an issue template

### ISSUE THREAD

**Issue by MuhammadRabi** [zero-to-mastery/ZtM-Job-Board#2929]
I would like to propose creating an issue template for this repo

issue templates help in writing issues faster and guides creators to share information effectively. You can include instructions or specific formatting in the issue description as well as apply certain fields such as labels. It's also possible to set default templates for teams.

I would like to work on this.

**Comment by sophiabrandt** [comment]
Feel free to generate a template. Thanks for contributing to this repo.

**Comment by sophiabrandt** [comment]
Your commit was merged. I will close this now. Thank you.
