### ISSUE TITLE
[Bug] "show more" Btn doesn't show cursor pointer

### ISSUE THREAD

**Issue by MuhammadRabi** [zero-to-mastery/ZtM-Job-Board#2937]
**Describe the bug**
The "show more" button doesn't show cursor pointer on hovering

**To Reproduce**
1. Go to the Homepage
2. Scroll down to the lower part of the page
4. hover the "show more" button

**Expected behavior**
the button should show a cursor pointer when hovering over it to indicate it is clickable

**Screenshots**

![bug9000](https://github.com/zero-to-mastery/ZtM-Job-Board/assets/34184092/52a3943a-f063-441d-bd89-5f91eba10bd2)

**Additional context**
I would like to fix this

**Checklist**

By submitting this issue, you agree to follow our Code of Conduct:

- [x] I have read the [Contributors' Guide](https://github.com/zero-to-mastery/resources/blob/master/CONTRIBUTING.md).
- [x] I have checked the existing [issues](https://github.com/zero-to-mastery/ZtM-Job-Board/issues).
- [x] I am willing to work on this issue (optional).

**Comment by l-white** [comment]
@MuhammadRabi This functionality is working for me. Which browser are you using?

**Comment by MuhammadRabi** [comment]
> @MuhammadRabi This functionality is working for me. Which browser are you using?

I'm using Google Chrome, it does not show too on Brave and Firefox.

**Comment by Chinwenma** [comment]
@MuhammadRabi  that is actually true the show more button does not show cursor pointer on hover.

**Comment by l-white** [comment]
@MuhammadRabi I see the issue. You can submit a change for this, but we will not be changing much functionality in this repo because it's meant for simple changes for students who are just starting out.

**Comment by MuhammadRabi** [comment]
@l-white, Yes I understand that. Thanks for the clarification.
