### ISSUE TITLE
Add a go to top button

### ISSUE THREAD

**Issue by Saikatssd** [zero-to-mastery/ZtM-Job-Board#3023]
🐞 **Problem**

There no go to top button so it become difficult for the user to go to top.

📋  **Steps to solve the problem**

*  I will add a go to top button so it becomes easy for a person to come to the front page.
        
By submitting this issue, you agree to follow our Code of Conduct:

- [ ] I have read the [Contributors' Guide](https://github.com/zero-to-mastery/resources/blob/master/CONTRIBUTING.md).
- [ ] I have checked the existing [issues](https://github.com/zero-to-mastery/ZtM-Job-Board/issues).
- [ ] I am willing to work on this issue (optional).

**Comment by Saikatssd** [comment]
Please assign me to contribute on this

**Comment by Tejaso7** [comment]
I would like to work on it .

**Comment by sophiabrandt** [comment]
This seems to be already done if you check the website. I'm closing this issue.
