### ISSUE TITLE
[Docs]:- Adding code of conduct to repo.

### ISSUE THREAD

**Issue by mohitd404** [zero-to-mastery/ZtM-Job-Board#3031]
**Describe the bug**
We propose adding a comprehensive Code of Conduct to our repository to ensure a safe, respectful, and inclusive environment for all contributors and users. This code will serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a wider range of perspectives.

**Checklist**

By submitting this issue, you agree to follow our Code of Conduct:

- [ ✅] I have read the [Contributors' Guide](https://github.com/zero-to-mastery/resources/blob/master/CONTRIBUTING.md).
- [ ✅] I have checked the existing [issues](https://github.com/zero-to-mastery/ZtM-Job-Board/issues).
- [ ✅] I am willing to work on this issue (optional).

**Comment by mohitd404** [comment]
kindly assign this issue to me !!

**Comment by sophiabrandt** [comment]
Thank you for your suggestion. Currently we do not want to add a separate Code of conduct document.
