### ISSUE TITLE
Better UI could be a plus

### ISSUE THREAD

**Issue by anish1204** [zero-to-mastery/ZtM-Job-Board#3243]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Checklist**

By submitting this issue, you agree to follow our Code of Conduct:

- [x] I have read the [Contributors' Guide](https://github.com/zero-to-mastery/resources/blob/master/CONTRIBUTING.md).
- [x] I have checked the existing [issues](https://github.com/zero-to-mastery/ZtM-Job-Board/issues).
- [x] I am willing to work on this issue (optional).

**Comment by sophiabrandt** [comment]
That's true. Better UI is always a plus.

Do you have a specific suggestion on what you want to improve?

**Comment by anish1204** [comment]
![Screenshot (420)](https://github.com/zero-to-mastery/ZtM-Job-Board/assets/91008239/d332e6c2-321c-422a-9052-0b28da243db1)

The website is great 
As you could see the second section (total user and countries) is kind of basic looking
Also the color theme could be improvised with background image and a combination of( blue black white , or possibly more) patter usage.

Thinking of adding a 3d elements which might improve the user experience

**Comment by anish1204** [comment]
Also i think on hover on a card it must enlarge a little bit and the other remaining part should dull out a liitle bit 
Whats your thought on it?

**Comment by anish1204** [comment]
Could you assign this issue to me ??

**Comment by ksachin7** [comment]
Assign it to me. I have already updated a lot of things in my local. I'll update it tonight.

**Comment by ksachin7** [comment]
Please merge it. I've updated the UI with significant changes, including updates to the Card component and the Navbar. However, some issues have been observed with the card footer as you can see in the screenshot. I will fix it later.
![20240813_000819](https://github.com/user-attachments/assets/3dbdf3c7-f52e-4772-aaef-7406aeea32e6)

**Comment by ksachin7** [comment]
I'm not able to create a pull request for it, Its showing: These branches can be automatically merged. @sophiabrandt

**Comment by farooq13** [comment]
please what is the **difference** between the two? ``UI``

**Comment by ksachin7** [comment]
I added and modified some scss, redesign card and make it wider, added some icons to the navbar. Overall it looks better than before.

**Comment by farooq13** [comment]
That is great!

**Comment by sophiabrandt** [comment]
This was already assigned to @anish1204 .
Are you still interested in this?

@ksachin7 feel free to make a new pull request with your changes. I'll see if we can consolidate the changes a little bit.

**Comment by sophiabrandt** [comment]
@anish1204 any update on this?
Otherwise I will close this issue for now. A pull request is always possible if the changes are within reason.
