### ISSUE TITLE
[BUG] The filter method

### ISSUE THREAD

**Issue by roberthugsy** [zero-to-mastery/ZtM-Job-Board#367]
As developers we tend to use full stack, full-stack and fullstack in our profiles. Nothing bad with that, but can we add regex to fix the search and find all the fullstack developers?

Same for frontend, etc.

I will try to get into it and make a pull request.

**Comment by MattCSmith** [comment]
@roberthugsy Sounds great, look forward to seeing this implemented :)

**Comment by Oghenebrume50** [comment]
I did something I think it works now,  check it out

**Comment by roberthugsy** [comment]
It works for me, for both space and '-' char.
