### ISSUE TITLE
[suggestion] I think we should incorporate a registration page 

### ISSUE THREAD

**Issue by Oghenebrume50** [zero-to-mastery/ZtM-Job-Board#385]
So, following the first implementation of issue  #310 , I noticed a lot of  #things.
1. Some developers do  not correctly spell their location
2. Some developers add extra details to their location name e.g (willing to relocate)
3. Huge use of inappropriate abbreviations 
4. The API used to get latitude and longitude doesn't recognize England to be a country(*wink*), but somewhere in the UK.

Now all this makes extracting location details from the person.js object very difficult, a registration page with a backend server will solve this issue and make the site more cool, plus more developers will be rendered on the map What do you guys think?

**Comment by wptechprodigy** [comment]
Nice feature to add.
However, I think the present method of inclusion is to help students learn about contributing to open source.
So, adding an object that includes a student info into the file is a great way for many to learn.

I think having a registration form on the FE defeats this objective.

**Comment by Oghenebrume50** [comment]
@wptechprodigy yeah you are right

**Comment by GousosGas** [comment]
Is someone working on developing a Rest Api?
