### ISSUE TITLE
Create a new input method

### ISSUE THREAD

**Issue by willianwelbert** [zero-to-mastery/ZtM-Job-Board#51]
Check if it's possible to build a form to register people data, maybe save information as a .json file inside the repository. This will avoid discrepancy between data formats and allow employers to navigate better through candidates

**Comment by SamirJouni** [comment]
That's a very good idea ! If you can modify the project to work this way and make a pull request of that, I would personally approve of it. :)
It might take a lot of javascript to get that to work, but I suppose it is possible. Though using a database and a backend to process the data would be more suitable. Anyway, if you can make it work on the client side, then that would be an amazing contribution to this project ! 
If I had the time to do it myself, I would have gotten to it now. My apologies for my lack of time. :)
