### ISSUE TITLE
unable to push request

### ISSUE THREAD

**Issue by rizwanrajput** [zero-to-mastery/ZtM-Job-Board#648]
![image](https://user-images.githubusercontent.com/50185178/62338489-2e193500-b4f2-11e9-9c88-2408ce68976a.png)

**Comment by Mirhatyasar** [comment]
if you don't have permission to push to master branch you can't push.

**Comment by rizwanrajput** [comment]
I just wanted to add my name on job board.

**Comment by Mirhatyasar** [comment]
Open Cmd 
cd ZtM-Job-Board
add your name to file on your text editor
save it
go cmd again and do: 
git status
git add [filename]
git commit -m"message"
git push origin master
go github and merge or admin will do it

**Comment by rizwanrajput** [comment]
PS C:\Users\rizwa\documents\GitHub\ZtM-Job-Board> git push origin master                                                remote: Permission to zero-to-mastery/ZtM-Job-Board.git denied to rizwanrajput.                                         fatal: unable to access 'https://github.com/zero-to-mastery/ZtM-Job-Board.git/': The requested URL returned error: 403

**Comment by Mirhatyasar** [comment]
you  need to fork project then clone forked project and try to push

**Comment by rizwanrajput** [comment]
> Open Cmd or you can use Git bash and follow the commands
> cd ZtM-Job-Board
> add your name to file on your text editor
> save it
> go cmd again and do:
> git status
> git add filename
> git commit -m"message"
> git push origin master
> go github and merge if you can't merge admin will do it

I forked the project here https://github.com/rizwanrajput/ZtM-Job-Board and followed above instructions. What to do next? (after git push origin master)

**Comment by Mirhatyasar** [comment]
did you clone the forked project? copy the forked project's link and then do:
git clone -link-
and then follow instructions

**Comment by Dhaval1403** [comment]
> > Open Cmd or you can use Git bash and follow the commands
> > cd ZtM-Job-Board
> > add your name to file on your text editor
> > save it
> > go cmd again and do:
> > git status
> > git add filename
> > git commit -m"message"
> > git push origin master
> > go github and merge if you can't merge admin will do it
> 
> I forked the project here https://github.com/rizwanrajput/ZtM-Job-Board and followed above instructions. What to do next? (after git push origin master)

After pushing the files to your forked version follow the below steps.
1) Go to https://github.com/rizwanrajput/ZtM-Job-Board (Forked Version)
2) Make a Pull Request (PR) by clicking on the button "Compare and make a PR" and that's all
3) The admins gets the notification about your PR and if they approve it then they'll merge it into the original repository.

Hope that helps :)
