### ISSUE TITLE
As the list grows, maybe could be a good idea to random how the list is displayed

### ISSUE THREAD

**Issue by luisFebro** [zero-to-mastery/ZtM-Job-Board#671]
**Suggestion**
I have a suggestion to change a static list to a more dynamic list with random position in every new load. This way, the last added programmers (including the current first static programmers) can have the opportunity to be displayed in the first columns when a new recruiter scroll down the page. 

I have created a function from [another project](https://luisfebro.github.io/threehundredjs/) of mine to get an array with random indices to iterate through a group of fellow programmers from another community (it was a JS hall of fame).  With this following function I made sure to display random order in every new load in the page.

```javascript
function getRandomArray(arrLength) {
    arrLength--;
    var newRandomArray = [];

    var ind = 0;
    for (; ind <= arrLength; ind++) {
        newRandomArray.push(ind);
    }

    newRandomArray.sort(function(a, b) {
        return 0.5 - Math.random();
    });

    return newRandomArray;
}
```

**Comment by Gigi1111** [comment]
I agree with Luis' suggestion. Was just thinking the same thing.

**Comment by Filat1** [comment]
Here is Durstenfeld shuffle algorithm, a computer-optimized version of Fisher-Yates:

function shuffleArray(array) {
    for (var i = array.length - 1; i > 0; i--) {
        var j = Math.floor(Math.random() * (i + 1));
        var temp = array[i];
        array[i] = array[j];
        array[j] = temp;
    }
}


Seems it is faster. It has O(n) time complexity 
algorithm works by picking one random element for each original array element, and then excluding it from the next draw. Just like randomly picking from a deck of cards.
This exclusion is done in a clever way (invented by Durstenfeld for use by computers) by swapping the picked element with the current element, and then picking the next random element from the remainder.
