### ISSUE TITLE
why i am getting this error 

### ISSUE THREAD

**Issue by Blacky-dev** [zero-to-mastery/ZtM-Job-Board#741]
remote: Permission to zero-to-mastery/ZtM-Job-Board.git denied to Blacky-dev.
fatal: unable to access 'https://github.com/zero-to-mastery/ZtM-Job-Board.git/': The requested URL returned error: 403

**Comment by Dhaval1403** [comment]
Hey @Blacky-dev 
Are you trying to push your files directly on the original repository??  If so, then it could be the reason because you don't have admin rights to push your files directly onto the original repository. Hope that helps :)

**Comment by Blacky-dev** [comment]
Nope even though i tried to push files by branching ,it was giving me the
same error..
