### ISSUE TITLE
[Suggestion] An optional remote job availability check in persons.json

### ISSUE THREAD

**Issue by abhishekakade** [zero-to-mastery/ZtM-Job-Board#759]
## Problem
A lot of people have been adding `(Remote/Available anywhere for remote jobs, etc)` to their `country` value in `persons.json` instead of just the country name.

## Effects
This is causing country location fetches and map to fail as we are using the same `country` value in the restcountries API to add a marker on Google maps. And the country name value needs to be very accurate for the fetch request to succeed.

## Solution
We should add a new optional key `remote` to every `id` to see if developers are interested in remote jobs with value as `true/false`. And then if the user has `remote` value, we can add it to their card on the job board.

**Comment by sophiabrandt** [comment]
I think that's a good idea, but you will also have to adjust the previous data in `persons.json`.
Feel free to make an implementation and make a pull request.
Or anyone else who is interested!
