### ISSUE TITLE
Improve search logic to include location and deprecated_location

### ISSUE THREAD

**Issue by aparadox** [zero-to-mastery/ZtM-Job-Board#91]
If #90 is accepted,some work will be required to make sure the search feature searches through `deprecated_location` AND through `location`.

Also, the Name radio button should be selected by default on page load.

**Comment by thomasdreyer** [comment]
done, waiting for merge!

**Comment by Ekidoxx** [comment]
About searching: Soon won't be needed, as `robots.js` will be updated to new structure

About radio button: Well, so far I have no damn idea how to fix this one xd
