### ISSUE TITLE
Deprecated Website

### ISSUE THREAD

**Issue by JacintoDesign** [zero-to-mastery/ZtM-Job-Board#96]
My name is Jacinto Wong and I just added my info last week. My website link appears as 'deprecated_website' even though the link and website work. I guess it could be because it is a .design instead of a .com

**Comment by TzuHsuan** [comment]
It's because that's what you have between the a tags, which you probably copied from somewhere else.

**Comment by Ekidoxx** [comment]
Fixing that in meanwhile of updating whole `robots.js` ...
